name: Post Merge auto Clean

on:
  pull_request:
    types: [closed]
    paths:
      - '**.ipynb'

jobs:
  clean_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Get list of changed .ipynb files
        id: get_changed_files
        run: |
          git fetch --prune --unshallow
          git diff --name-only HEAD^ HEAD | grep '\.ipynb$' | jq -R -s -c 'split("\n")[:-1]' > changed_files.json
          echo "files=$(cat changed_files.json)" >> $GITHUB_OUTPUT
      - name: Clean up .ipynb files
        run: |
          files='${{ steps.get_changed_files.outputs.files }}'
          echo "$files" | jq -c '.[]' | while read -r file; do
            file=$(echo "$file" | jq -r '.')
            echo "Cleaning up ${file}"
            nb_helpers.fix_nbs "${file}"
          done
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Clean Up
          file_pattern: '*.ipynb'
          repository: .